In [49]:
import pandas as pd
import numpy as np
from scipy.ndimage import label

# Load the Excel file (adjust the file name/path as needed)
df = pd.read_excel("Test_Data.xlsx", header=None)

# Convert the DataFrame to a NumPy array.
# Non-NaN cells are considered part of a table.
data = df.values

# Create a boolean mask: True for non-empty cells, False for empty ones.
mask = ~pd.isna(data)

# Perform connected component analysis using an 8-connectivity structure.
structure = np.ones((3, 3), dtype=int)
labeled, ncomponents = label(mask, structure=structure)

# Initialize a dictionary to hold the tables as DataFrames.
table_dict = {}

# Loop over each connected component (each "table")
for component in range(1, ncomponents + 1):
    # Get the indices (row, col) where the component is present
    indices = np.argwhere(labeled == component)
    if indices.size == 0:
        continue

    # Determine the bounding box for the component
    rows = indices[:, 0]
    cols = indices[:, 1]
    rmin, rmax = rows.min(), rows.max()
    cmin, cmax = cols.min(), cols.max()

    # Extract the table using the bounding box (include the end indices)
    table_df = df.iloc[rmin:rmax+1, cmin:cmax+1]
    
    # Store the DataFrame in the dictionary using a descriptive key.
    table_dict[f"table_{component}"] = table_df

# Example: Access and print each table DataFrame
for name, table in table_dict.items():
    print(f"\n{name}:")
    print(table)

table_1:
      11        12        13
0     ID  Lineage       OPER
1    555        T1     _mavd
2    222        T3  _hujrfwe
3    333        T4    _dfhhf
4    444        T5   _hfhfgd
5  22233        T6    _jkglg

table_2:
                             1
1  THE ECONOMICS OF THE WORLD
2                 IT IS GREAT

table_3:
         1         2                3           4            5             6   \
8   Mapiing  Lineage   Transofrmation           ID         Teat         gjFGY
9         1      Bess       MacSkeagan      Female        Jasen       Kettles
10        2    Wallis       Dinnington        Male       Claire         Paute
11        3   Jeramie           Lowman        Male        Olwen      Augustus
12        4   Corella       O'Glassane      Female       Tracey         Ellen
13        5  Ricoriki        Gomersall        Male        Byrle       Bendare
14        6    Tandie        Caseborne      Female     Broderic       Adamoli
15        7       Pip         Pragnell        Male  Christopher     McCrackan
16        8   Ingunna           Paddie      Female       Curran          Maud
17        9  Claudine           Iacomo      Female        Aguie         Kidde
18       10       Hal           Genike  Polygender        Jilli   De Robertis
19       11    Candra            Hunte      Female        Nedda        Rumgay
20       12    Jessee          Humbles        Male        Hanan        Hawyes
21       13     Bogey         Rentalll        Male     Rochella        Baford
22       14      Jack        Robillard        Male       Evered    Normanvell
23       15    Jelene          Carlill      Female       Pennie       Annable
24       16   Charity         Kempston      Female        Rasia  Calderonello
25       17     Worth           Shreve        Male       Lissie   Goldsworthy
26       18      Pier           Creboe     Agender         Livy      Quainton
27       19  Berkeley          Grassin        Male       Blayne      Doughill
28       20     Pedro         Tambling        Male       Hermie      Mildmott
29       21     Adams        Eastbrook        Male       Trista       Holdron
30       22   Abigale          Peschke      Female       Reuben         Soldi
31       23     Sibel    Thundercliffe    Bigender        Eldin        Traice
32       24     Lolly         Scatchar      Female       Devina         McKee
33       25     Vikky            Beeby  Polygender    Priscilla       Stamper
34       26   Malvina           Sutter      Female       Anthia        Grelik

                                 7            8           9             10  \
8                             GHJKM       HNJHJN          HH         HJKJM
9          jkettles17@reference.com     Bigender        Nomi     Gracewood
10             cpaute18@pcworld.com   Polygender       Hersh         Boome
11          oaugustus19@t-online.de       Female      Jennie      Roderick
12               tellen1a@topsy.com       Female       Nolie         Laven
13        bbendare1b@shareasale.com         Male     Malinda       Poulsum
14             badamoli1c@naver.com         Male      Hester           Key
15        cmccrackan1d@stanford.edu         Male     Conrado         Tothe
16             cmaud1e@bandcamp.com         Male       Karla  Setterington
17                  akidde1f@gov.uk         Male       Conni      Gossipin
18            jderobertis1g@npr.org       Female       Kelsi     Cheeseman
19                nrumgay1h@last.fm       Female    Meredith        Dredge
20            hhawyes1i@archive.org         Male      Bailie         Rigge
21             rbaford1j@smh.com.au      Agender        Bale         Guiso
22           enormanvell1k@digg.com  Genderqueer       Jarid       McElree
23            pannable1l@nature.com         Male      Libbey        Bowers
24  rcalderonello1m@fastcompany.com       Female     Ingemar      Grunbaum
25        lgoldsworthy1n@cpanel.net       Female     Olympia    Hemmingway
26            lquainton1o@prweb.com       Female       Darya   Baszkiewicz
27         bdoughill1p@japanpost.jp         Male        Ward       O'Nions
28           hmildmott1q@drupal.org         Male       Aimee       Paybody
29             tholdron1r@cisco.com       Female       Paten        Sumers
30      rsoldi1s@washingtonpost.com         Male     Arluene     Learmount
31               etraice1t@blog.com         Male      Weidar       Dunster
32         dmckee1u@theatlantic.com       Female     Brandea         Meere
33               pstamper1v@usa.gov       Female  Sigismundo  Groomebridge
34                agrelik1w@cdc.gov       Female      Konrad      Kobierra

                             11        12
8                          EERt     rweer
9       ngracewood2a@cdbaby.com     T1.JG
10           hboome2b@intel.com   T2.jhuy
11       jroderick2c@github.com  T3.terew
12     nlaven2d@fastcompany.com     T1.JG
13         mpoulsum2e@imgur.com   T2.jhuy
14      hkey2f@chronoengine.com  T3.terew
15             ctothe2g@wsj.com     T1.JG
16      ksetterington2h@icio.us   T2.jhuy
17  cgossipin2i@paginegialle.it  T3.terew
18          kcheeseman2j@ca.gov     T1.JG
19       mdredge2k@so-net.ne.jp   T2.jhuy
20               brigge2l@de.vu  T3.terew
21         bguiso2m@samsung.com     T1.JG
22         jmcelree2n@nifty.com   T2.jhuy
23     lbowers2o@washington.edu  T3.terew
24  igrunbaum2p@nydailynews.com     T1.JG
25    ohemmingway2q@dedecms.com   T2.jhuy
26   dbaszkiewicz2r@nbcnews.com  T3.terew
27          wonions2s@tmall.com     T1.JG
28    apaybody2t@eventbrite.com   T2.jhuy
29  psumers2u@timesonline.co.uk  T3.terew
30         alearmount2v@mtv.com     T1.JG
31         wdunster2w@nymag.com   T2.jhuy
32             bmeere2x@ted.com  T3.terew
33      sgroomebridge2y@wix.com     T1.JG
34         kkobierra2z@ucoz.com   T2.jhuy

In [50]:
table_dict["table_1"]

      11        12        13
0     ID  Lineage       OPER
1    555        T1     _mavd
2    222        T3  _hujrfwe
3    333        T4    _dfhhf
4    444        T5   _hfhfgd
5  22233        T6    _jkglg

In [51]:
table_dict["table_2"]

                             1
1  THE ECONOMICS OF THE WORLD
2                 IT IS GREAT

In [52]:
table_dict["table_3"]

,1,2,3,4,5,6,7,8,9,10,11,12
8,Mapiing,Lineage,Transofrmation,ID,Teat,gjFGY,GHJKM,HNJHJN,HH,HJKJM,EERt,rweer
9,1,Bess,MacSkeagan,Female,Jasen,Kettles,jkettles17@reference.com,Bigender,Nomi,Gracewood,ngracewood2a@cdbaby.com,T1.JG
10,2,Wallis,Dinnington,Male,Claire,Paute,cpaute18@pcworld.com,Polygender,Hersh,Boome,hboome2b@intel.com,T2.jhuy
11,3,Jeramie,Lowman,Male,Olwen,Augustus,oaugustus19@t-online.de,Female,Jennie,Roderick,jroderick2c@github.com,T3.terew
12,4,Corella,O'Glassane,Female,Tracey,Ellen,tellen1a@topsy.com,Female,Nolie,Laven,nlaven2d@fastcompany.com,T1.JG
13,5,Ricoriki,Gomersall,Male,Byrle,Bendare,bbendare1b@shareasale.com,Male,Malinda,Poulsum,mpoulsum2e@imgur.com,T2.jhuy
14,6,Tandie,Caseborne,Female,Broderic,Adamoli,badamoli1c@naver.com,Male,Hester,Key,hkey2f@chronoengine.com,T3.terew
15,7,Pip,Pragnell,Male,Christopher,McCrackan,cmccrackan1d@stanford.edu,Male,Conrado,Tothe,ctothe2g@wsj.com,T1.JG
16,8,Ingunna,Paddie,Female,Curran,Maud,cmaud1e@bandcamp.com,Male,Karla,Setterington,ksetterington2h@icio.us,T2.jhuy
17,9,Claudine,Iacomo,Female,Aguie,Kidde,akidde1f@gov.uk,Male,Conni,Gossipin,cgossipin2i@paginegialle.it,T3.terew
18,10,Hal,Genike,Polygender,Jilli,De Robertis,jderobertis1g@npr.org,Female,Kelsi,Cheeseman,kcheeseman2j@ca.gov,T1.JG
19,11,Candra,Hunte,Female,Nedda,Rumgay,nrumgay1h@last.fm,Female,Meredith,Dredge,mdredge2k@so-net.ne.jp,T2.jhuy
20,12,Jessee,Humbles,Male,Hanan,Hawyes,hhawyes1i@archive.org,Male,Bailie,Rigge,brigge2l@de.vu,T3.terew
21,13,Bogey,Rentalll,Male,Rochella,Baford,rbaford1j@smh.com.au,Agender,Bale,Guiso,bguiso2m@samsung.com,T1.JG
22,14,Jack,Robillard,Male,Evered,Normanvell,enormanvell1k@digg.com,Genderqueer,Jarid,McElree,jmcelree2n@nifty.com,T2.jhuy
23,15,Jelene,Carlill,Female,Pennie,Annable,pannable1l@nature.com,Male,Libbey,Bowers,lbowers2o@washington.edu,T3.terew
24,16,Charity,Kempston,Female,Rasia,Calderonello,rcalderonello1m@fastcompany.com,Female,Ingemar,Grunbaum,igrunbaum2p@nydailynews.com,T1.JG
25,17,Worth,Shreve,Male,Lissie,Goldsworthy,lgoldsworthy1n@cpanel.net,Female,Olympia,Hemmingway,ohemmingway2q@dedecms.com,T2.jhuy
26,18,Pier,Creboe,Agender,Livy,Quainton,lquainton1o@prweb.com,Female,Darya,Baszkiewicz,dbaszkiewicz2r@nbcnews.com,T3.terew
27,19,Berkeley,Grassin,Male,Blayne,Doughill,bdoughill1p@japanpost.jp,Male,Ward,O'Nions,wonions2s@tmall.com,T1.JG
28,20,Pedro,Tambling,Male,Hermie,Mildmott,hmildmott1q@drupal.org,Male,Aimee,Paybody,apaybody2t@eventbrite.com,T2.jhuy
29,21,Adams,Eastbrook,Male,Trista,Holdron,tholdron1r@cisco.com,Female,Paten,Sumers,psumers2u@timesonline.co.uk,T3.terew
30,22,Abigale,Peschke,Female,Reuben,Soldi,rsoldi1s@washingtonpost.com,Male,Arluene,Learmount,alearmount2v@mtv.com,T1.JG
31,23,Sibel,Thundercliffe,Bigender,Eldin,Traice,etraice1t@blog.com,Male,Weidar,Dunster,wdunster2w@nymag.com,T2.jhuy
32,24,Lolly,Scatchar,Female,Devina,McKee,dmckee1u@theatlantic.com,Female,Brandea,Meere,bmeere2x@ted.com,T3.terew
33,25,Vikky,Beeby,Polygender,Priscilla,Stamper,pstamper1v@usa.gov,Female,Sigismundo,Groomebridge,sgroomebridge2y@wix.com,T1.JG
34,26,Malvina,Sutter,Female,Anthia,Grelik,agrelik1w@cdc.gov,Female,Konrad,Kobierra,kkobierra2z@ucoz.com,T2.jhuy